apiVersion: v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-service
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service
      # below image should be changed based on the code was changed
        image: 
        resources:
           requests:
             memory: "125Mi"
             cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "500m"
----
# service
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    name: user-service
  ports:
  - protocol: TCP
    port: 80 #container port
    targetPort: 8761 #service port
  type: NodePort



              
